### ISSUE TITLE
hl2sdk on darwin

### ISSUE THREAD

**Issue by tucnak** [alliedmodders/hl2sdk#1]
Hey there

You guys are doing really well with this modding and related. Still, I got a huge trouble with porting existing plugin from windows to mac. I had a bunch of issues, like "Unsupported platform" and "Unknown architecture" here. Looks like in some cases I need to define it better.

I am building on latest OS X with latest gcc/g++ with cmake 2.8.10.2.

Can anybody help me out?

**Comment by tucnak** [comment]
I already defined -DPOSIX -DGNUC -DOSX in order to get rid of some platform errors.

**Comment by tucnak** [comment]
**mathlib.h:1220**

```
FORCEINLINE int RoundFloatToInt(float f)
{
#if defined(__i386__) || defined(_M_IX86) || defined( PLATFORM_WINDOWS_PC64 )
    return _mm_cvtss_si32(_mm_load_ss(&f));
#elif defined( _X360 )
#ifdef Assert
    Assert( IsFPUControlWordSet() );
#endif
    union
    {
        double flResult;
        int pResult[2];
    };
    flResult = __fctiw( f );
    return pResult[1];
#else
#error Unknown architecture
#endif
}
```

Getting #error out. Looks like I should define `__i386__` or `_M_IX86` here. Right?

**Comment by tucnak** [comment]
Just defined `__i386__` as a temporary solution.

```
/Users/tucnak/Development/hl2/sdk/public/tier1/utlstring.h:310: error: call to 'wcschr' is ambiguous
    static const wchar_t *FindChar( const wchar_t *pStr, const wchar_t cSearch ) { return wcschr( pStr, cSearch ); }
                                                                                          ^~~~~~
```

Guys, I am really lost with this crap. Btw, I had to comment `#include <malloc.h>` in one of files, because it's not here.

**Comment by tucnak** [comment]
Please, anyone, e-mail me. This shit got me whole.

**Comment by TheDS** [comment]
1. Which branch of the SDK are you working with?
2. Which game is the plugin supposed to work with?
3. Are you actually using gcc/g++ or is it really clang? Later versions of Xcode include a gcc binary that is actually clang. You can check for sure by running `gcc --version` in Terminal.
4. You shouldn't have to define `__i386__` if you are building with the `-m32` flag. 
5. In which header file did you have to comment out the `#include <malloc.h>`?

**Comment by tucnak** [comment]
1. I am working with current master
2. Team Fortress 2 (P-REC)
3. Just checked it and you are right – it is clang. Wtf, gonna get old good gcc from homebrew. Nice catch! Am I right that _good_ gcc is critical here?
4. Build with `-m32`, you mean g++ argument?
5. I realised that on my system I don't have `malloc.h` include at all, so I commented it on `memdbgon.h:36`.

**Comment by asherkin** [comment]
You need to use the 'tf2' branch for tf2 plugin development.

**Comment by tucnak** [comment]
Oh, sounds reasonable.

**Comment by psychonic** [comment]
> You need to use the 'tf2' branch for tf2 plugin development.

P-REC is a client plugin. The master/sdk2013 branch will track much more closely.

**Comment by tucnak** [comment]
@psychonic, I am basically trying to get some builds for Mac/Linux, so you got it, yeah.
