### ISSUE TITLE
[Question] engine for client interfaces i.e. in CSS?

### ISSUE THREAD

**Issue by dtugend** [alliedmodders/hl2sdk#15]
Hello.

I am just curious, if there is a chance, that you'll update the engine for client interfaces somewhen, or if they are beyond your scope, meaning you care only about server interfaces?

Because if you care about the former too, I wanted to inform you, that at least your CSS VEngineClient013 interface is out of date, it almost matches the Source SDK 2013 interface now, apart from i.e.
- GetLightForPoint has 3 instead of 2 parameters
- GetLightForPointFast has 3 instead of 2 parameters
- USE_SDL is false
- The VEngineClient014 interface has an additional function somewhere after FlashWindow

I read somewhere that you reverse engineer your interfaces from the MAC binaries, if so I sadly probably can't help much with that, because I don't have a MAC and don't know how to download MAC binaries on Windows or Linux, even though there might be a way maybe.

With kind regards

**Comment by psychonic** [comment]
We don't maintain the headers for client interfaces.

As you suggested, it is beyond our scope. Additionally, the primary use for them seems to be cheat development.

**Comment by dtugend** [comment]
Thank you for your quick reply.

I understand and respect your answer.

I admit that they would be used by cheaters heavily, but those work them out anyway, just don't publish them.

In case you wondered, I am personally interested in them, since I develop [HLAE / AfxHookSource](https://github.com/ripieces/advancedfx).

**Comment by ghost** [comment]
> We don't maintain the headers for client interfaces.
> 
> As you suggested, it is beyond our scope. Additionally, the primary use for them seems to be cheat development.

I still think their uses outweights their consequences. Incorporating them sounds like something you should still consider maintaining.
