### ISSUE TITLE
FGDLib for csgo branch

### ISSUE THREAD

**Issue by jonatan1024** [alliedmodders/hl2sdk#19]
Hi,
Could you add headers for fgdlib into the csgo branch?
Thanks

**Comment by psychonic** [comment]
Apologies for the late response.

This just isn't feasible for us. The headers will not do much good without also having the updated fgdlib lib itself for CS:GO. The one currently in that branch is carried over from the Alien Swarm SDK and likely doesn't match CS:GO.

Additionally, no sources for the library have been released with any of the official SDKs, so working adjusting from there won't work either.
