### ISSUE TITLE
problem compile plugins mysql_mm. network_connection.pb.h

### ISSUE THREAD

**Issue by metacop** [alliedmodders/hl2sdk#194]
problem when compiling a mysql_mm plugins, and it gives me an error in the eiface.h file of the cs2 branch, there is an include on "network_connection.pb.h" and not even this file in that branch. what is the problem?

![image](https://github.com/alliedmodders/hl2sdk/assets/56640826/d938b2a0-4b3b-499d-bed6-eadb9ffd4c7c)

![image](https://github.com/alliedmodders/hl2sdk/assets/56640826/55bfe186-0723-4b0a-a5f5-06742cea8ead)

**Comment by psychonic** [comment]
That file is generated from network_connection.proto

**Comment by DiDHack** [comment]
```
protoc --cpp_out=/work/vendor/hl2sdk/public/engine \
        -Icommon/ \
        common/network_connection.proto
```
