### ISSUE TITLE
[CS2 metamod plugin] undefined symbol: _ZNK15CEntityIdentity11NameMatchesEPKc)

### ISSUE THREAD

**Issue by DiDHack** [alliedmodders/hl2sdk#205]
Can somebody help? After yesterday's update metamod was bkoken. I updated hl2sdk, metamod is compiled and works.
After changing the variable reason in the function ClientDisconnect of my plugin from int to ENetworkDisconnectionReason it is compiled too. But if I try to load the plugin I get the error:
`undefined symbol: _ZNK15CEntityIdentity11NameMatchesEPKc).`
I don't use CEntityIdentity::NameMatches in my plugin

I tried to compile the sample from metamod. There is the same error.

**Comment by toorisrael** [comment]
Make sure you include this line in your script:
https://github.com/Source2ZE/CS2Fixes/blob/main/AMBuilder#L81

**Comment by DiDHack** [comment]
Thank you!
This error is resolved.
But I got the next:
`undefined symbol: _Z16GameEntitySystemv`

os.path.join(sdk.path, 'entity2', 'entitysystem.cpp'), included

I think the issue in this line:
`g_pGameEntitySystem = *reinterpret_cast<CGameEntitySystem**>(reinterpret_cast<uintptr_t>(g_pGameResourceServiceServer) + WIN_LINUX(0x58, 0x50));`

**Comment by DiDHack** [comment]
I found the solution
```
CGameEntitySystem* GameEntitySystem()
{
    return g_pUtils->GetCGameEntitySystem();
};
```
`g_pGameEntitySystem = GameEntitySystem();`
