### ISSUE TITLE
tchar compilation errors?

### ISSUE THREAD

**Issue by RusJJ** [alliedmodders/hl2sdk#222]
Hello! Im having a lot of compilation errors related to the tchar usage in a code (using CS2 branch):
![image](https://github.com/alliedmodders/hl2sdk/assets/8864329/edf81ee1-5ec4-4415-9161-bfaf8df305b0)

The error says an obvious thing about "tchar" that cannot be used as a "char". What am i doing wrong..? (Developing a metamod plugin)

VS2022, Win10, compiling for x64.
Preprocessor definitions: COMPILER_MSVC COMPILER_MSVC64 META_IS_SOURCE2

**Comment by RusJJ** [comment]
Well, i think it's gonna be abandoned.

**Comment by betsch85** [comment]
your solution probably uses Unicode, switch to Multi-Byte and it'll go away

**Comment by RusJJ** [comment]
It is, i forgot to change multibyte for **__x64__**...
