### ISSUE TITLE
sdktools crashes due to recent tf2 update on certain cpus

### ISSUE THREAD

**Issue by bottiger1** [alliedmodders/hl2sdk#231]
The new TF2 update broke GetCPUInformation() for at least 1 of my cpus. This function is dynamically linked to in libtier0_srv.so.

It shows the intel cpu as having 3dnow an AMD only instruction set and not having SSE. So when NormalizeVector is called, the server crashes due to running AMD only code. This doesn't seem to be an issue on every CPU.

I don't know if this will be fixed so maybe it's worth not using the game for basic math operations like this.

**Comment by Jugheadbomb** [comment]
Having the same issue, server crashes on `NormalizeVector`

CPU: AMD Opteron(tm) Processor 6386 SE
OS: linux x32

**Comment by engvin** [comment]
I'm sorry, I'm asking a question at a more primitive level.

After the update, server crashes when using things related to aim tracing, for example targeting player with @aim command; using plugins such as 'spawn building at aim', 'teleport player to aim'. Super Spray Handler or Spray Manager crash the server when you try to connect (those plugins always check if you are aiming at the spray, as I understand it).

Is this related to the problem you are talking about? Thank you!

**Comment by Jugheadbomb** [comment]
@minimal138 yea, this is related to the problem, everything that uses `NormalizeVector` (maybe some other functions) causes crash

**Comment by asherkin** [comment]
@bottiger1 @Jugheadbomb @minimal138 Please could you edit your comments to include which platform and model CPU you're using.

**Comment by psychonic** [comment]
Could one of you give SourceMod `1.12.7119` or `1.11.6958` a try to see if it resolves the issue? (Linux builds are available now, Windows will be shortly)

**Comment by engvin** [comment]
@psychonic 1.11.6958 resolved the issue for me, thanks!

p.s. still dont know the linux version and CPU I have, hoster's tech support is slow

**Comment by Jugheadbomb** [comment]
Seems issue is still here, crashes on
```|
Program terminated with signal SIGILL, Illegal instruction.
#0  0xe38abdc8 in _3DNow_VectorNormalize(Vector&) () from /game/tf/addons/sourcemod/extensions/sdktools.ext.2.tf2.so
```

Both sourcemod and metamod latest build

**Comment by psychonic** [comment]
There was another comment that mentioned the issue still being present, however, that comment looks to have been edited or removed.

I pushed some additional fixes, and new builds are in progress. Would you mind verifying again that everything is still working as intended once those are available? (The version number should end up being +1 from the ones I listed in my previous comment)

**Comment by Jugheadbomb** [comment]
@psychonic I'm sorry, it was my comment.
Issue have been resolved after your previous hl2sdk-tf2 changes. It was my mistake: I just updated sm bins, but forgot to update extensions.

**Comment by engvin** [comment]
@psychonic `1.11.6959` works fine as well

**Comment by psychonic** [comment]
Thanks for checking
