### ISSUE TITLE
64bit compile fix

### ISSUE THREAD

**Issue by bottiger1** [alliedmodders/hl2sdk#236]
for hl2sdk-tf2 maybe more

change int to intptr_t

https://github.com/alliedmodders/hl2sdk/blob/78dab58646d5983c77af44c45a877b89196eb82c/public/networkvar.h#L25

`#define MyOffsetOf( type, var ) ( (intptr_t)&((type*)0)->var )`

**Comment by Kenzzer** [comment]
What motivated this change ?

**Comment by bottiger1** [comment]
it throws a compile error on 64bit
