### ISSUE TITLE
[L4D2] (May 14th) `KeyValues` structure updated

### ISSUE THREAD

**Issue by jensewe** [alliedmodders/hl2sdk#239]
![image-1](https://github.com/alliedmodders/hl2sdk/assets/33988868/2b03cdc7-ca57-47e1-8ec3-6aa9bc39ac76)

Similar to csgo's one:
https://github.com/alliedmodders/hl2sdk/blob/c758235e71d85ae43acaadedd237b5e8966d60e9/public/tier1/KeyValues.h#L335-L361

but looks missing an int32 at the end (`a1[10]`).

**Comment by jensewe** [comment]
Any plan/progress on updating KeyValues codes? There're still crashes ([`KeyValues::RemoveEverything`](https://crash.limetech.org/hcovu5dpohoz)) on my end about KeyValues extensions.

463d54462061c512b5a09833c9fed70b7b2dce96
I believe this should be what the updated code looks like, but perhaps because of not recompiled SourceMod I'm still getting [`free()` crashes](https://crash.limetech.org/2x2gjux33ra6) when deleting KeyValues handles.

Glad if any further information could be provided.

**Comment by Kenzzer** [comment]
Given that this issue wasn't reported until now, no progress/update has been made. But feel free to open a PR !

**Comment by Kenzzer** [comment]
I've taken a look at your commit history on your fork, any reason you stopped using Valve's MemAlloc ?

**Comment by jensewe** [comment]
It's simply because the updated binary shows `operator new/delete[]` instead of `malloc/free` when using Valve's allocator, and I blindly decided to give it a try. Leave it out if it's just wrong.

**Comment by jensewe** [comment]
May I ask for a trigger build at least on SM 1.11? 🤔
