### ISSUE TITLE
Remove IToolGameEventAPI, how to use event manager now?

### ISSUE THREAD

**Issue by DiDHack** [alliedmodders/hl2sdk#249]
Before I used:

`gameeventmanager = static_cast<IGameEventManager2*>(CallVFunc<IToolGameEventAPI*, 93>(g_pSource2Server));`

But now IToolGameEventAPI does not exists

I tried to use:

`gameeventmanager = static_cast<IGameEventManager2*>(CallVFunc<IGameEventManager2*, 93>(g_pSource2Server));`

It is compiled but does not work. Segmentation fault.

**Comment by GAMMACASE** [comment]
You need to get it by other means now.

**Comment by DiDHack** [comment]
I understand it, but how? I have tried a solution whole previous day. Could you give me a hint or a clue as to where to look?

**Comment by GAMMACASE** [comment]
As an example, https://github.com/Source2ZE/CS2Fixes/commit/fec0eb8332ef58d559cc85d6bc6ec5377c0d561b.

**Comment by DiDHack** [comment]
Thank you!
