### ISSUE TITLE
Ordered comparison of function pointer gives compilation error while I was compiling Metamod:Source

### ISSUE THREAD

**Issue by imrishhh** [alliedmodders/hl2sdk#259]
error: ordered comparison of function pointers ('SchemaCollectionManipulatorFn_t' (aka 'void *(*)(SchemaCollectionManipulatorAction_t, void *, void *, void *)') and 'SchemaCollectionManipulatorFn_t') [-Werror,-Wordered-compare-function-pointers]
                return m_pfnManipulator < rhs.m_pfnManipulator;
                
               Cs2 branch

**Comment by Wend4r** [comment]
Error/Warning is output by Clang
![image](https://github.com/alliedmodders/hl2sdk/assets/47463683/fb340b39-4f67-422a-ac84-86524dc900fb)

There is no such thing on GCC

https://github.com/alliedmodders/hl2sdk/pull/253

**Comment by GAMMACASE** [comment]
Currently the solution is to use ``-Wno-ordered-compare-function-pointers`` flag, and I'm not sure there are plans on any other fix for this.

**Comment by imrishabk** [comment]
> Currently the solution is to use `-Wno-ordered-compare-function-pointers` flag, and I'm not sure there are plans on any other fix for this.

Yeah it works after using this flag.

I tried to use using std::less function object which seems to help with compiling. Not sure if its a good practice


`return std::less<SchemaCollectionManipulatorFn_t>()(m_pfnManipulator, rhs.m_pfnManipulator);`

**Comment by GAMMACASE** [comment]
Well that warning got quite annoying over time, so I've took another look at it, and indeed, ``std::less`` does seem to be working fine, but it requires an inclusion of stl library (specifically ``<functional>``) which I don't think we want to do. Instead I've just went with a more harsh "fix" and just casted it to ``void*`` which seems to retained its functionality and resolved the warning.
