### ISSUE TITLE
License

### ISSUE THREAD

**Issue by L-EARN** [alliedmodders/hl2sdk#27]
Hi,

I just need some help to correct one point about the licensing of the sdks.

I used you versions along with the original source sdk 2013 to produce a _dynamic_ sdk [here](https://github.com/L-EARN/SourceSdk-ServerPlugin]) and I just wanted to know if the licenses (Including Google's protobuf) are compatible with the license I choosed for [this plugin](https://github.com/L-EARN/NoCheatZ-4).

It's not like I can't read licenses but I just have troubles understanding them.

Thanks if you ever answer this.

**Comment by psychonic** [comment]
We can't give you legal advice here. We're not lawyers.
