### ISSUE TITLE
Missing branch ob-valve

### ISSUE THREAD

**Issue by satoon101** [alliedmodders/hl2sdk#28]
The old mercurial repository had a branch for the Valve OB games called ob-valve.  Is there a reason that branch was never brought over to this repository?  I assume it was just missed, but perhaps there was a reason.  The link states that the branch is here:
https://hg.alliedmods.net/hl2sdks/hl2sdk-ob/

The reason I ask is that I am fairly certain that the ob-valve branch is the one that we (the Source.Python dev team) need to build against to get our plugin working for Valve single-player games.  It would be awesome if that branch was brought over.

**Comment by psychonic** [comment]
The equivalent to the hl2sdk-ob repo is the orangebox branch on the hl2sdk repo.

There is no direct equivalent to the hl2sdk-ob-valve repo. After Valve started updating games on this branch at different intervals, it was split into the css, tf2, dods, and hl2dm branches. At first, everything but CS:S was getting updated regularly, and then in more recent times, only TF2 is. We keep separate SDKs for each of these games to account for this.

The Valve single player games actually lag even further behind. We do not currently have a branch for them.

**Comment by psychonic** [comment]
Actually, the Valve single player games should track directly, or at least closely with the official source-sdk-2013 sp folder.

**Comment by satoon101** [comment]
Thank you for the quick response.

Unfortunately, the orangebox branch gives me all sorts of errors when building primarily due to the memalloc.h file having not been updated since 2008.  Rather than try to continue down that path and patch everything to death, I decided to manually download and build against the ob-valve branch.  Once I got everything setup properly, it built fine and the plugin loads fine on HL2: Ep2.

I tried the sdk2013 branch, as well, but it crashes to desktop when loading it in HL2: Ep2.  Though, I haven't looked fully into why that happens, yet.

**Comment by satoon101** [comment]
Oh, I just realized I linked to the wrong branch in my OP.  I meant this one:
https://hg.alliedmods.net/hl2sdks/hl2sdk-ob-valve/

**Comment by psychonic** [comment]
The sdk2013 branch tracks the "mp" folder of the official source-sdk-2013. The old ob-valve would indeed probably be closer for HL2, but the "sp" folder of the official one should be exact or near. It's very rare that they update the single player games anymore.

**Comment by KyleSanderson** [comment]
Which platform are you having trouble with? Have you tried defining POSIX?

**Comment by jimster480** [comment]
The hl2DM CSS and TF2 branches are all fairly close now.
The difference is minimal at best and mostly related to netvars.

**Comment by satoon101** [comment]
HL2DM, CSS, TF2, and DODS are not an issue, as we already use their respective branches to build against.

The current issue is getting a version built that works for Valve single player games (HL2, its Episodes, and Portal).  None of those branches works for the single player games.  They all contain a newer version of IVEngineServer than the single player games.  sdk2013 has the correct version of IVEngineServer, but it crashes to desktop on plugin_load, prior to initializing Python.

I have only attempted to build on Windows, so far.  I want to get it working on that platform before moving onto Linux.

**Comment by jimster480** [comment]
Engine server I am not sure about. But the HL2 single player games were all
on orange box engine v2.
Valves entire versioning has gotten completely out of hand, every single
game is slightly different from every other game.
But the single player games haven't been updated at all in years so if you
have older headers they should build fine and match up.
If you are crashing I suggest you find the exact function that is
misaligned and then Space the SDK out.

**Comment by psychonic** [comment]
>  sdk2013 has the correct version of IVEngineServer, but it crashes to desktop on plugin_load

If you haven't already, can you see if the same issue occurs when compiling against https://github.com/ValveSoftware/source-sdk-2013/tree/master/sp/src

> But the HL2 single player games were all on orange box engine v2.

It's all semantics, but I'd say that there's both been one version, and been many versions. It's always been a rolling target, constantly updated, but not all games on the branch actually have updates released at the same time.
