### ISSUE TITLE
Is it possible to add 64-bit support to hl2sdk-css?

### ISSUE THREAD

**Issue by 1922828151** [alliedmodders/hl2sdk#286]
I got a 64-bit Linux CS source dedicated server, but I can't build metamod and sourcemod for it.

**Comment by Kenzzer** [comment]
Hello! I'm a bit out of the loop concerning CSS, when has it received 64bits support ?
I'm not seeing any 64bits binaries in CSS dedicated server files :
https://steamdb.info/depot/232336/

**Comment by 1922828151** [comment]
This is a version that adds support for mobile devices. It can build 32/64-bit games and dedicated servers for Windows/Linux/Android platforms. https://github.com/nillerusr/source-engine


> Hello! I'm a bit out of the loop concerning CSS, when has it received 64bits support ? I'm not seeing any 64bits binaries in CSS dedicated server files : https://steamdb.info/depot/232336/

**Comment by Kenzzer** [comment]
Putting the legality issue of such a project aside, trying to distribute SM & MMS builds for this project would require us to maintain hl2sdk-css with the changes this team makes, and they might divert from baseline so much that it starts breaking 32bits compilation, which would then require us to further edit hl2sdk-css, for that reason on top of the legal issue we won't try to make any move.

I instead suggest that you reach out to them, and ask if they can provide you with builds of SM & MMS, unlike for us this shouldn't be much work for them to compile, and they'd be better equipped to fix the future compilation issues (if they arise) with SM & MMS.
