### ISSUE TITLE
TF2 Navmesh

### ISSUE THREAD

**Issue by Kenzzer** [alliedmodders/hl2sdk#32]
Hello I ran into a small problem recently, and I need some help over it.
I don't really know how valve's sdk2013 repo is organized, but i have noticed that while going through tf2 server code, at [NavAreaTravelDistance](https://github.com/alliedmodders/hl2sdk/blob/sdk2013/game/server/nav_pathfind.h#L435) function, GetParent() which is in fact m_parent, is differing of 4 bytes from the value given in the sdk2013 repo:

`v6 = *(_DWORD *)(v6 + 120);`
https://github.com/ValveSoftware/source-sdk-2013/blob/master/mp/src/game/server/nav_area.h#L249

So I'm not sure if I can safely use the functions provided from that repo with a CNavArea pointer from the server.

**Comment by psychonic** [comment]
With a couple of exceptions, we don't generally keep files under game/* up to date. PRs are welcome though.
