### ISSUE TITLE
Sync sdk2013 with Valve

### ISSUE THREAD

**Issue by GoD-Tony** [alliedmodders/hl2sdk#4]
Requesting a sync with the latest changes from Valve's 2013 repo. Mostly for easy browsing with the MXR site.

**Comment by psychonic** [comment]
That has intentionally not been done yet. Unfortunately, not all mods are using the latest version of the 2013 SDK yet (due to mods distributed on Steam having the option not to update). We don't want to have newer functions available (and thus, potentially attempted to be used) on those mods.

**Comment by GoD-Tony** [comment]
Fair enough!
