### ISSUE TITLE
[Dota 2] GameEventHandle_t__->m_MessageID incorrect values

### ISSUE THREAD

**Issue by stanriders** [alliedmodders/hl2sdk#40]
It worked fine until ~yesterday. Now it's giving almost random results for each usermsg. I'm hooking IGameEventSystem::PostEventAbstract here:
```
(gdb) print pEvent->m_MessageID
$1 = 1
(gdb) print pEvent->m_szMessageType
$2 = 0x9c6b4f8 "CDOTAUserMsg_GamerulesStateChanged [506]"
```

```
(gdb) print pEvent->m_MessageID
$3 = 1599360513
(gdb) print pEvent->m_szMessageType
$4 = 0x9c9e478 "CDOTAUserMsg_UnitEvent [488]"
```

**Comment by psychonic** [comment]
A cursory look suggests that the ID is at +24 now (was +48) on 64-bit.

Try removing m_pUnknown3, 4, and 5.

**Comment by psychonic** [comment]
I must have been looking at a different structure. Checking it at runtime now, it's at +20 on 32-bit (one unknown removed). Commit to fix is incoming.
