### ISSUE TITLE
[Question] Some missing non-public directories

### ISSUE THREAD

**Issue by ghost** [alliedmodders/hl2sdk#58]
I'm curious about the discrepancies I've noticed between the 2007 SDK and this one. For example, where is [networksystem](https://github.com/VSES/SourceEngine2007/tree/master/src_main/networksystem)? Has it been removed or has its contents been dispersed into other parts of the SDK due to legitimate valve updates?

**Comment by asherkin** [comment]
The repository linked contains a leaked copy of the full Source engine code base, not the public SDK subset we track here - as far as I know the `networksystem` directory has never been included in any public HL2SDK code drops.
