### ISSUE TITLE
Update usercmd.h to fix wrong read on PlayerRunCmd for game PVKII

### ISSUE THREAD

**Issue by PlayBoy31** [alliedmodders/hl2sdk#73]
A missing member cause to read wrong data on CUserCmd struct => server_random_seed has been added for the game PVKII.

A same correction has been done one BMS, see https://github.com/alliedmodders/hl2sdk/pull/72

Tested with this same correction and it works but a new SDK branch for PVKII must be created. Talk to this with @psychonic but he propose another solution.

Solution from @psychonic : 

> A much better solution is just converting that functionality to use gamedata. dealing with the cusercmd memory instead of using the sdk class, so that sdk updates/additions aren't needed for cases like these

I d'ont know how to implement this

**Comment by psychonic** [comment]
There are a couple issues at play here, but I'm not sure that it's anything we can or want to take action on from the SDK perspective.

First, the SDK does have this field on the sdk2013 branch. I suspect that SourceMod or the SDKTools extension is just not defining GAME_DLL (and probably should be, but that could have other implications). It looks like we just have the define check commented out on the BMS branch to avoid the need for that.

The slightly bigger issue is that some mods may have the field or may not, depending on when they last merged in changes from Valve. While it hasn't been updated in a while, the base Source SDK 2013 code can update at any time, and mods can take or not take those changes. We have Valve's latest code here. Valve does take care to make sure that the public interfaces don't break for mods, but this struct is internal to the mod itself.

I think a better approach, which was mentioned in the original comment, is to change SDKTools to use gamedata to be able to dynamically handle cases like this. We're fairly lucky that more breakage doesn't occur with it already.
