### ISSUE TITLE
hl2sdk-csgo Mistake introduced in IAppSystem?

### ISSUE THREAD

**Issue by dtugend** [alliedmodders/hl2sdk#9]
I have a question regarding [this commit](https://github.com/alliedmodders/hl2sdk/commit/0ef5c3c95101e364a987bdc270ccde6613be48b4):

It introduces an IsSingleton function

However when I look at my vstdlib.dll from the current CS:GO version:
] version
Protocol version 13483
Exe version 1.34.8.3 (csgo)
Exe build: 15:15:43 Apr 28 2015 (5949) (730)

The vtable for VEngineCvar007 / ICvar doesn't include that IsSingleton function, instead at it's place there is already the AllocateDLLIdentifier function from the ICvar / VEngineCvar007 interface.

Is the mistake on my end?

**Comment by asherkin** [comment]
That version output is not up-to-date for the server.

The last update (which was optional and probably server-only) was 11 days ago on May 14th, and changed that interface.

**Comment by dtugend** [comment]
Ok thank you.
I was only watching at the CS:GO game (not the dedicated server).
